[package]
name = "skyspace"
version = "0.1.4"
authors = ["Christopher Dumas <christopherdumas@gmail.com>",
"William Trovinger <william.trovinger@icloud.com"]

[dependencies]
tcod = "0.11"
tcod-sys = "*"
rand = "0.3.12"